#!/bin/bash
curr_dir="$(pwd)"
location="${curr_dir/"$AGENT_DIR"/}"
export guide_dir="$HQ_DATA_DIR$location"
export progress="$guide_dir/progress.txt"
guide_script="$guide_dir/guide.sh"
notebook_dir="$HQ_DATA_DIR/notebook"
export unlocked_notebook_dir="$notebook_dir/unlocked"
export pages_notebook_dir="$notebook_dir/pages"

#text variables
export hili=$(tput setab 1)
export typecolb=$(tput setaf 4)
export typecolg=$(tput setaf 2)
export typecolw=$(tput setaf 7)
export bold=$(tput bold)
export norm=$(tput sgr0)

# returns 0 if the notebook was not already unlocked
function unlock_notebook() {
    name="$1"
    display_name="$2"
    if [ ! -f "$unlocked_notebook_dir/$name.sh" ]
    then
        mv "$pages_notebook_dir/$name.sh" "$unlocked_notebook_dir/$name.sh"
        echo "You have unlocked the notebook entry for $display_name"
        echo "Use ${hili}notebook${norm} to view it"
        return 0
    fi
}

function hqunlock() {
    find "$HQ_DATA_DIR" -name hqlock -delete
}

function hqlock() {
    hqunlock
    cd "$guide_dir"
    touch "$1/hqlock"
    cd "$curr_dir"
}

export -f unlock_notebook
export -f hqunlock
export -f hqlock

if [[ "$curr_dir" =~ "headquarters" ]]
then
    cat "$HQ_DATA_DIR/headquarters_readme.txt"
    exit 0
fi

if [ -f "$guide_script" -a ! -x "$guide_script" ]
then
    chmod +x "$guide_script"
fi

if [ -f "$guide_script" ]
then
    export lock_loc="$(find "$HQ_DATA_DIR" -name hqlock)"
    if [ -z "$lock_loc" -o "$guide_dir/hqlock" = "$lock_loc" ]
    then
        "$guide_dir/guide.sh" $*
    else
        "$HQ_DATA_DIR/get_back_over_here_young_man.sh"
    fi
elif [[ "$curr_dir" =~ ".files" ]]
then
    "$HQ_DATA_DIR/dubai_technology_associates/Documents/.files/filemaze.sh" $*
else
    "$HQ_DATA_DIR/lost.sh" $*
fi
