#!/bin/bash
curr_dir="$(pwd)"
location="${curr_dir/"$AGENT_DIR"/}"
export guide_dir="$HQ_DATA_DIR$location"
export progress="$guide_dir/progress.txt"
guide_script="$guide_dir/guide.sh"

#text variables
export hili=$(tput setab 1)
export typecolb=$(tput setaf 4)
export typecolg=$(tput setaf 2)
export typecolw=$(tput setaf 7)
export bold=$(tput bold)
export norm=$(tput sgr0)

if [[ "$curr_dir" =~ "headquarters" ]]
then
    cat "$HQ_DATA_DIR/headquarters_readme.txt"
    exit 0
fi

if [ -f "$guide_script" -a ! -x "$guide_script" ]
then
    chmod +x "$guide_script"
fi

if [ -f "$guide_script" ]
then
    "$guide_dir/guide.sh" $*
elif [[ "$curr_dir" =~ ".files" ]]
then
    "$HQ_DATA_DIR/dubai_technology_associates/Documents/.files/filemaze.sh" $*
else
    "$HQ_DATA_DIR/lost.sh" $*
fi
