#!/bin/bash
export hili=$(tput setab 1)
export typecolb=$(tput setaf 4)
export typecolg=$(tput setaf 2)
export typecolw=$(tput setaf 7)
export typecolr=$(tput setaf 1)
export bold=$(tput bold)
export norm=$(tput sgr0)

notebook_dir="$HQ_DATA_DIR/notebook"
unlocked_notebook_dir="$notebook_dir/unlocked"

rm -f "$notebook_dir/notebook.txt"

for i in $unlocked_notebook_dir/*
do
    if [ -z "$i" ]
    then
        exit 0
    fi
    if [ ! -x "$i" ]
    then
        chmod +x "$i"
    fi
    "$i" >> "$notebook_dir/notebook.txt"
    echo >> "$notebook_dir/notebook.txt"
done

less -R "$notebook_dir/notebook.txt"
