#!/bin/bash
echo "${bold}chmod${norm}"
echo "	chmod allows you to change the permission on a file."
echo "	The octal syntax is as follows: chmod 000 (file)"
echo "	The octal numbers are as files:"
echo "	0 : No permissions"
echo "	1 : Execute permission only"
echo "	2 : Write permission only"
echo "	3 : Write and execute permissions"
echo "	4 : Read permission only"
echo "	5 : Read and execute permissions"
echo "	6 : Read and write permissions"
echo "	7 : Read, write and execute permissions"
