echo "Welcome to the training area"
echo "I told you the name of the file but you will not always know in the investagation"
echo "Use the command ls to list all the files in a the current directory"
echo "A blue name represents a directory"
echo "A green name represents a script"
echo "And a white name represents a normal file"
echo "once you find the directory enter it using cd then use hq to get your next instructions"
